In [5]:
import tensorflow as tf
  
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = (x1 * w1) + (x2 * w2) + (x3 * w3) + b

# cost/Loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()

# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
  cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
  
  if step % 100 == 0:
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  52848.914 
Prediction:
 [-58.43853  -56.70121  -63.03264  -65.532646 -42.598267]
100 Cost:  12.249643 
Prediction:
 [145.64343 188.35306 178.54744 197.52014 144.27563]
200 Cost:  11.728942 
Prediction:
 [145.76613 188.2697  178.58598 197.54063 144.17247]
300 Cost:  11.235187 
Prediction:
 [145.88562 188.18854 178.62354 197.56046 144.07216]
400 Cost:  10.76691 
Prediction:
 [146.00198 188.10948 178.66014 197.57959 143.97462]
500 Cost:  10.322756 
Prediction:
 [146.11536 188.03253 178.69582 197.59808 143.87982]
600 Cost:  9.901484 
Prediction:
 [146.22575 187.95758 178.73059 197.61592 143.78763]
700 Cost:  9.501909 
Prediction:
 [146.33328 187.88461 178.76447 197.63312 143.69801]
800 Cost:  9.122858 
Prediction:
 [146.438   187.8135  178.79749 197.64973 143.6109 ]
900 Cost:  8.76325 
Prediction:
 [146.54004 187.74432 178.82968 197.66577 143.52621]
1000 Cost:  8.422106 
Prediction:
 [146.6394  187.67694 178.86107 197.68124 143.44388]
1100 Cost:  8.098387 
Prediction:
 [146.7362  

In [13]:
import tensorflow as tf
  
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

# placeholders for a tensor that will be always feed
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight1')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

# cost/Loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()

# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
  cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
  
  if step % 100 == 0:
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  4557.259 
Prediction:
 [[204.87263]
 [260.82486]
 [249.47061]
 [272.2767 ]
 [201.97554]]
100 Cost:  17.57047 
Prediction:
 [[145.2599 ]
 [188.8639 ]
 [178.7281 ]
 [195.21992]
 [147.02667]]
200 Cost:  16.657516 
Prediction:
 [[145.42032]
 [188.75409]
 [178.77742]
 [195.25418]
 [146.88377]]
300 Cost:  15.79276 
Prediction:
 [[145.57645]
 [188.6472 ]
 [178.82544]
 [195.28746]
 [146.74472]]
400 Cost:  14.973523 
Prediction:
 [[145.72844]
 [188.54317]
 [178.87221]
 [195.31987]
 [146.6094 ]]
500 Cost:  14.197545 
Prediction:
 [[145.87636]
 [188.4419 ]
 [178.91771]
 [195.35135]
 [146.47772]]
600 Cost:  13.462463 
Prediction:
 [[146.02036]
 [188.34332]
 [178.962  ]
 [195.38197]
 [146.3496 ]]
700 Cost:  12.766157 
Prediction:
 [[146.1605 ]
 [188.24739]
 [179.00514]
 [195.41174]
 [146.2249 ]]
800 Cost:  12.10655 
Prediction:
 [[146.29692]
 [188.154  ]
 [179.04712]
 [195.4407 ]
 [146.10355]]
900 Cost:  11.481684 
Prediction:
 [[146.42973]
 [188.06311]
 [179.08798]
 [195.46884]
 [145.9854

In [46]:
# Loading data from file
from google.colab import drive
drive.mount('/content/gdrive')

import numpy as np

xy = np.loadtxt('/content/gdrive/My Drive/dataset/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

# placeholders for a tensor that will be always feed
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight1')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

# cost/Loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()

# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
  cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
  
  if step % 1000 == 0:
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
    
# Ask my score
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Ohter scores will be ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))


Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]
0 Cost:  146837.48 
Prediction:
 [[-206.78519]
 [-249.16643]
 [-245.10269]
 [-266.62582]
 [-190.67657]
 [-140.6381 ]]
1000 Cost:  2.4061358 
Prediction:
 [[152.60498]
 [183.41908]
 [180.80992]
 [197.17029]
 [139.44266]
 [102.73377]]
2000 Cost:  2.1556847 
Prediction:
 [[152.40303 ]
 [183.53706 ]
 [180.74397 ]
 [197.0543  ]
 [139.65857 ]
 [102.866585]]
Your score will be  [[182.09775]]
Ohter scores will be  [[162.7875 ]
 [180.03133]]


In [72]:
# Loading data from file
# Using tensorflow queue runners 

from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

import numpy as np

filename_queue = tf.train.string_input_producer(['/content/gdrive/My Drive/dataset/data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

# placeholders for a tensor that will be always feed
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight1')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

# cost/Loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()

# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

# Start populating the filename queue
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
  x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
#   cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
#   if step % 10 == 0:
#       print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

# # Minimize
# coord.request_stop()
# coord.join(threads)

Mounted at /content/gdrive
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Expect 4 fields but have 1 in record 0
	 [[{{node DecodeCSV_7}}]]


OutOfRangeError: ignored